### ISSUE TITLE
AR Foundation with OpenCV for Unity

### ISSUE THREAD

**Issue by yezun** [EnoxSoftware/ARFoundationWithOpenCVForUnityExample#2]
Hi,
I am trying to detect colors from the environment using AR Foundation in unity.I  used ARFoundationWithOpenCVForUnityExample but it is giving this error ( Assets\ARFoundationWithOpenCVForUnityExample\ARFoundationCameraArUcoExample\ARFoundationCameraArUcoExample.cs(144,9): error CS0246: The type or namespace name 'DetectorParameters' could not be found)（Assets\ARFoundationWithOpenCVForUnityExample\ARFoundationCameraArUcoExample\ARFoundationCameraArUcoExample.cs(149,9): error CS0305: Using the generic type 'Dictionary<TKey, TValue>' requires 2 type arguments）
（Assets\ARFoundationWithOpenCVForUnityExample\ARFoundationCameraArUcoExample\ARFoundationCameraArUcoExample.cs(623,33): error CS0117: 'Aruco' does not contain a definition for 'DICT_4X4_50'----------.cs(639,41): error CS0117: 'Aruco' does not contain a definition for 'DICT_ARUCO_ORIGINAL'
and OpenCV for Unity is 2.5.1 
would you please guide me in this regard?
Thank You.

**Comment by EnoxSoftware** [comment]
Thanks for the report.
With the latest opencv changes, the example using the ArUco class no longer works.
We will have a fix for this soon, but until then, please remove the "ArFoundationCameraArUcoExample" to suppress the error.

**Comment by EnoxSoftware** [comment]
Fixed issue.
